/**
 * Application enums, ported from the Prisma schema. Oracle has no native ENUM,
 * so these are stored as VARCHAR2 and validated in the app. Values are identical
 * to the former Prisma enums so they interoperate during the migration.
 */

export enum JobType {
  ORDER_SYNC = 'ORDER_SYNC',
  INVENTORY_SYNC = 'INVENTORY_SYNC',
  PAYMENT_SYNC = 'PAYMENT_SYNC',
  CONFIG_SYNC = 'CONFIG_SYNC',
  REFUND_SYNC = 'REFUND_SYNC',
  /** Operator-triggered region+date-range run: Odoo pull → daily invoices → full Oracle cycle. */
  INTEGRATION_RUN = 'INTEGRATION_RUN',
}

export enum ScopeType {
  SINGLE_ORDER = 'SINGLE_ORDER',
  DATE_RANGE = 'DATE_RANGE',
  BRANCH = 'BRANCH',
  BRANCH_DATE_RANGE = 'BRANCH_DATE_RANGE',
  ALL = 'ALL',
  FAILED_ONLY = 'FAILED_ONLY',
}

export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
  CANCELLED = 'CANCELLED',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  VALIDATED = 'VALIDATED',
  PROCESSING = 'PROCESSING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  QUEUED_FOR_RETRY = 'QUEUED_FOR_RETRY',
  NEGATIVE_INVENTORY_HOLD = 'NEGATIVE_INVENTORY_HOLD',
}

export enum AuditOperation {
  CREATE_INVOICE = 'CREATE_INVOICE',
  CREATE_RECEIPT = 'CREATE_RECEIPT',
  CREATE_CREDIT_MEMO = 'CREATE_CREDIT_MEMO',
  CREATE_JOURNAL = 'CREATE_JOURNAL',
  SYNC_INVENTORY = 'SYNC_INVENTORY',
  UPDATE_CONFIG = 'UPDATE_CONFIG',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  RETRY = 'RETRY',
  SKIPPED = 'SKIPPED',
  DUPLICATE = 'DUPLICATE',
}

export enum ValidationStatus {
  PENDING = 'PENDING',
  VALIDATED = 'VALIDATED',
  INVALID = 'INVALID',
  PARTIAL = 'PARTIAL',
}

export enum ErrorType {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  MAPPING_ERROR = 'MAPPING_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
  DUPLICATE_ERROR = 'DUPLICATE_ERROR',
  INVENTORY_ERROR = 'INVENTORY_ERROR',
  PAYMENT_METHOD_ERROR = 'PAYMENT_METHOD_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum InventoryTransactionType {
  SALE = 'SALE',
  RETURN = 'RETURN',
  ADJUSTMENT = 'ADJUSTMENT',
  RECEIPT = 'RECEIPT',
  TRANSFER = 'TRANSFER',
}

export enum ServiceName {
  ODOO_API = 'ODOO_API',
  ORACLE_SOAP = 'ORACLE_SOAP',
  ORACLE_REST = 'ORACLE_REST',
  REDIS = 'REDIS',
  DATABASE = 'DATABASE',
  WEBHOOK = 'WEBHOOK',
}

export enum HealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  UNHEALTHY = 'UNHEALTHY',
  UNKNOWN = 'UNKNOWN',
}

export enum NotificationRole {
  ADMIN = 'ADMIN',
  FINANCE = 'FINANCE',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  IT_SUPPORT = 'IT_SUPPORT',
  STORE_MANAGER = 'STORE_MANAGER',
}

export enum AlertType {
  PAYMENT_METHOD_DISCOVERED = 'PAYMENT_METHOD_DISCOVERED',
  NEGATIVE_INVENTORY = 'NEGATIVE_INVENTORY',
  STORE_CONFIG_INVALID = 'STORE_CONFIG_INVALID',
  SYNC_FAILURE = 'SYNC_FAILURE',
  CONNECTION_LOST = 'CONNECTION_LOST',
  DUPLICATE_DETECTED = 'DUPLICATE_DETECTED',
  REFUND_DETECTED = 'REFUND_DETECTED',
  SYNC_STALLED = 'SYNC_STALLED',
  ORACLE_CONNECTION_FAILED = 'ORACLE_CONNECTION_FAILED',
  ORACLE_PERFORMANCE_DEGRADED = 'ORACLE_PERFORMANCE_DEGRADED',
  ORACLE_CONNECTION_RECOVERED = 'ORACLE_CONNECTION_RECOVERED',
  INVALID_ORACLE_ITEM = 'INVALID_ORACLE_ITEM',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum SaleStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum ReceiptType {
  STANDARD = 'STANDARD',
  MISC = 'MISC',
  APPLY = 'APPLY',
}
