import type { FieldDef } from '@/components/admin/generic-admin-table';

// Common system fields always hidden in forms
export const SYS_FIELDS: FieldDef[] = [
  { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
  { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
  { key: 'updatedAt', label: 'Updated', type: 'date', readOnly: true, tableHidden: true },
];

export const ADMIN_TABLE_CONFIGS: Record<
  string,
  { title: string; fields: FieldDef[]; readOnly?: boolean; oracleTable?: string }
> = {
  'fusion-credentials': {
    title: 'Fusion Credentials',
    oracleTable: 'FUSION_CREDENTIALS',
    fields: [
      ...SYS_FIELDS,
      { key: 'hostName', label: 'Host Name', required: true },
      { key: 'server', label: 'Server', required: true },
      { key: 'username', label: 'Username', required: true },
      { key: 'password', label: 'Password', required: true },
      { key: 'active', label: 'Active', type: 'boolean' },
    ],
  },
  'vendhq-credentials': {
    title: 'VendHQ Credentials',
    oracleTable: 'VENDHQ_CREDENTIALS',
    fields: [
      ...SYS_FIELDS,
      { key: 'domainName', label: 'Domain Name', required: true },
      { key: 'personalToken', label: 'Personal Token', required: true },
      { key: 'region', label: 'Region', required: true },
      { key: 'currency', label: 'Currency' },
      { key: 'fusionOrgCode', label: 'Fusion Org Code' },
      { key: 'timezoneOffset', label: 'Timezone Offset', type: 'number' },
      { key: 'fusionTaxCode', label: 'Fusion Tax Code' },
      { key: 'businessStartDate', label: 'Business Start Date', type: 'date' },
      { key: 'active', label: 'Active', type: 'boolean' },
    ],
  },
  'odoo-credentials': {
    title: 'Odoo Credentials',
    fields: [
      ...SYS_FIELDS,
      { key: 'baseUrl', label: 'Base URL', required: true },
      { key: 'apiKey', label: 'API Key', required: true },
      { key: 'region', label: 'Region', required: true },
      {
        key: 'apiPath',
        label: 'API Path',
        description:
          'REST endpoint path used to fetch orders from this Odoo instance. ' +
          'Leave blank to auto-detect (tries /api/pos/order then /api/sale.order). ' +
          'Set explicitly if auto-detection fails — e.g. /api/pos/order for POS orders ' +
          'or /api/sale.order for sale orders.',
      },
      { key: 'active', label: 'Active', type: 'boolean' },
      {
        key: 'rejectUnauthorizedSsl',
        label: 'Verify SSL',
        type: 'boolean',
        description:
          'Uncheck only for dev/staging instances where the hostname does not match the SSL certificate (e.g. *.dev.odoo.com). Always keep checked for production.',
      },
      { key: 'lastSyncAt', label: 'Last Sync At', type: 'date', readOnly: true },
    ],
  },
  'outlet-config': {
    title: 'Outlet Integration Config',
    oracleTable: 'OUTLETS_INTEGRATION_CONFIG',
    fields: [
      ...SYS_FIELDS,
      { key: 'outletName', label: 'Outlet Name', required: true },
      { key: 'integMode', label: 'Integration Mode', required: true },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'fusion-bu-map': {
    title: 'Fusion Business Unit Map',
    oracleTable: 'FUSION_BUSINESS_UNIT_ID_MAP',
    fields: [
      ...SYS_FIELDS,
      { key: 'businessUnitId', label: 'Business Unit ID', type: 'number', required: true },
      { key: 'businessUnitName', label: 'Business Unit Name', required: true },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'fusion-receipt-methods': {
    title: 'Fusion Receipt Methods',
    oracleTable: 'FUSION_RECEIPT_METHOD',
    fields: [
      ...SYS_FIELDS,
      { key: 'receiptMethodId', label: 'Method ID', type: 'number', required: true },
      { key: 'receiptMethodName', label: 'Method Name', required: true },
      { key: 'receiptIsCash', label: 'Is Cash', type: 'boolean' },
      { key: 'receiptBankCharge', label: 'Bank Charge', type: 'number' },
      { key: 'receiptMethodTax', label: 'Method Tax', type: 'number' },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'fusion-sales-metadata': {
    title: 'Fusion Sales Metadata',
    oracleTable: 'FUSION_SALES_METADATA',
    fields: [
      ...SYS_FIELDS,
      { key: 'region', label: 'Region', required: true },
      { key: 'customerType', label: 'Customer Type', required: true },
      { key: 'billToName', label: 'Bill-To Name', required: true },
      { key: 'billToAccount', label: 'Bill-To Account', type: 'number', required: true },
      { key: 'siteNumber', label: 'Site Number' },
      { key: 'businessUnit', label: 'Business Unit', required: true },
      { key: 'txnSource', label: 'Txn Source', required: true },
      { key: 'txnType', label: 'Txn Type', required: true },
      { key: 'rateIsCorporate', label: 'Rate Is Corporate', type: 'boolean' },
      { key: 'recActivityNameBank', label: 'Rec Activity (Bank)' },
      { key: 'recActivityNameCash', label: 'Rec Activity (Cash)' },
      { key: 'subinventory', label: 'Subinventory' },
      { key: 'integrationSource', label: 'Integration Source', required: true },
      { key: 'distributionAccId', label: 'Distribution Acc ID', type: 'number' },
      { key: 'costCenterCode', label: 'Cost Center Code' },
    ],
  },
  'service-provider-journal-meta': {
    title: 'Service Provider Journal Meta',
    oracleTable: 'SERVICE_PROVIDER_JOURNAL_META',
    fields: [
      ...SYS_FIELDS,
      { key: 'region', label: 'Region', required: true },
      { key: 'serviceProvider', label: 'Service Provider', required: true },
      { key: 'ledgerId', label: 'Ledger ID', type: 'number', required: true },
      { key: 'taxGroupId', label: 'Tax Group ID', type: 'number' },
      { key: 'chartOfAccountsId', label: 'Chart of Accounts ID', type: 'number', required: true },
      { key: 'creditDebit', label: 'Credit/Debit' },
      { key: 'costIssue', label: 'Cost Issue' },
      { key: 'costRma', label: 'Cost RMA' },
      { key: 'company', label: 'Company' },
      { key: 'account', label: 'Account' },
      { key: 'department', label: 'Department' },
      { key: 'productCategory', label: 'Product Category' },
      { key: 'interCompany', label: 'Inter-Company' },
      { key: 'jeCategory', label: 'JE Category' },
      { key: 'jeSource', label: 'JE Source' },
      { key: 'isCash', label: 'Is Cash', type: 'boolean' },
      { key: 'summaryFlag', label: 'Summary Flag', type: 'boolean' },
      { key: 'fixedFreightCharge', label: 'Fixed Freight Charge', type: 'number' },
      { key: 'bankChargeRate', label: 'Bank Charge Rate', type: 'number' },
      { key: 'futUsed', label: 'Fut Used', tableHidden: true },
      { key: 'extraSegment1', label: 'Extra Segment 1', tableHidden: true },
      { key: 'extraSegment2', label: 'Extra Segment 2', tableHidden: true },
      { key: 'extraSegment3', label: 'Extra Segment 3', tableHidden: true },
    ],
  },
  'sales-integration-status': {
    title: 'Sales Integration Status',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'updatedAt', label: 'Updated', type: 'date', readOnly: true },
      { key: 'region', label: 'Region', required: true },
      { key: 'integMode', label: 'Integration Mode', required: true },
      { key: 'status', label: 'Status', required: true },
    ],
  },
  'vendhq-discount-items': {
    title: 'VendHQ Discount Items',
    oracleTable: 'VENDHQ_DISCOUNT_ITEMS',
    fields: [
      ...SYS_FIELDS,
      { key: 'discountItemId', label: 'Discount Item ID', required: true },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'vendhq-tax-meta': {
    title: 'VendHQ Tax Meta',
    oracleTable: 'VENDHQ_TAX_META',
    fields: [
      ...SYS_FIELDS,
      { key: 'taxId', label: 'Tax ID', required: true },
      { key: 'taxName', label: 'Tax Name', required: true },
      { key: 'version', label: 'Version', type: 'number' },
      { key: 'fusionName', label: 'Fusion Name' },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'vendhq-outlets': {
    title: 'VendHQ Outlets',
    oracleTable: 'VENDHQ_OUTLETS',
    fields: [
      ...SYS_FIELDS,
      { key: 'outletId', label: 'Outlet ID', required: true },
      { key: 'outletName', label: 'Outlet Name', required: true },
      { key: 'currency', label: 'Currency' },
      { key: 'version', label: 'Version', type: 'number' },
      { key: 'deletedAt', label: 'Deleted At', type: 'date' },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'vendhq-registers': {
    title: 'VendHQ Registers',
    oracleTable: 'VENDHQ_REGISTERS',
    fields: [
      ...SYS_FIELDS,
      { key: 'registerId', label: 'Register ID', required: true },
      { key: 'outletId', label: 'Outlet ID', required: true },
      { key: 'registerName', label: 'Register Name', required: true },
      { key: 'cashAccount', label: 'Cash Account' },
      { key: 'cashAccountId', label: 'Cash Account ID', type: 'number' },
      { key: 'bankAccount', label: 'Bank Account' },
      { key: 'bankAccountId', label: 'Bank Account ID', type: 'number' },
      { key: 'giftAccount', label: 'Gift Account' },
      { key: 'giftAccountId', label: 'Gift Account ID', type: 'number' },
      { key: 'version', label: 'Version', type: 'number' },
      { key: 'deletedAt', label: 'Deleted At', type: 'date' },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'vendhq-service-providers': {
    title: 'VendHQ Service Providers',
    oracleTable: 'VENDHQ_SERVICE_PROVIDERS',
    fields: [
      ...SYS_FIELDS,
      { key: 'region', label: 'Region', required: true },
      { key: 'serviceProvider', label: 'Service Provider', required: true },
      { key: 'vendHqCustomerId', label: 'VendHQ Customer ID' },
      { key: 'isCash', label: 'Is Cash', type: 'boolean' },
    ],
  },
  'vendhq-item-meta': {
    title: 'VendHQ Item Meta',
    fields: [
      ...SYS_FIELDS,
      { key: 'itemId', label: 'Item ID', required: true },
      { key: 'name', label: 'Name', required: true },
      { key: 'sku', label: 'SKU' },
      { key: 'uomCode', label: 'UOM Code' },
      { key: 'uomName', label: 'UOM Name', tableHidden: true },
      { key: 'handle', label: 'Handle', tableHidden: true },
      { key: 'itemType', label: 'Type' },
      { key: 'brandId', label: 'Brand ID', tableHidden: true },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'retailPrice', label: 'Retail Price', type: 'number' },
      { key: 'active', label: 'Active', type: 'boolean' },
      { key: 'trackInventory', label: 'Track Inventory', type: 'boolean', tableHidden: true },
      { key: 'description', label: 'Description', type: 'textarea', tableHidden: true },
      { key: 'region', label: 'Region', required: true },
    ],
  },
  'fusion-invoice-headers': {
    title: 'Fusion Invoice Headers',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'requestId', label: 'Request ID', type: 'number' },
      { key: 'billToCustName', label: 'Bill-To Customer' },
      { key: 'businessUnit', label: 'Business Unit' },
      { key: 'txnNumber', label: 'Txn Number', type: 'number' },
      { key: 'txnDate', label: 'Txn Date', type: 'date' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'message', label: 'Message', type: 'textarea', tableHidden: true },
      { key: 'paymentTermsName', label: 'Payment Terms', tableHidden: true },
      { key: 'txnSource', label: 'Txn Source', tableHidden: true },
      { key: 'txnType', label: 'Txn Type', tableHidden: true },
      { key: 'glDate', label: 'GL Date', type: 'date', tableHidden: true },
      { key: 'billToLocation', label: 'Bill-To Location', tableHidden: true },
      { key: 'billToAccNumber', label: 'Bill-To Acc#', type: 'number', tableHidden: true },
      { key: 'customerTxnId', label: 'Customer Txn ID', type: 'number', tableHidden: true },
    ],
  },
  'fusion-invoice-lines': {
    title: 'Fusion Invoice Lines',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'invoiceNumber', label: 'Invoice #' },
      { key: 'lineNumber', label: 'Line #', type: 'number' },
      { key: 'itemNumber', label: 'Item #' },
      { key: 'quantity', label: 'Qty', type: 'number' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'description', label: 'Description', tableHidden: true },
      { key: 'uom', label: 'UOM', tableHidden: true },
      { key: 'taxCode', label: 'Tax Code', tableHidden: true },
      { key: 'salesOrder', label: 'Sales Order', tableHidden: true },
    ],
  },
  'fusion-standard-receipts': {
    title: 'Fusion Standard Receipts',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'receiptNumber', label: 'Receipt #' },
      { key: 'receiptDate', label: 'Receipt Date', type: 'date' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'integMode', label: 'Mode', tableHidden: true },
      { key: 'receiptMethodId', label: 'Method ID', type: 'number', tableHidden: true },
      { key: 'customerId', label: 'Customer ID', type: 'number', tableHidden: true },
      { key: 'orgId', label: 'Org ID', type: 'number', tableHidden: true },
    ],
  },
  'fusion-misc-receipts': {
    title: 'Fusion Misc Receipts',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'receiptNumber', label: 'Receipt #' },
      { key: 'receiptDate', label: 'Receipt Date', type: 'date' },
      { key: 'receiptMethodName', label: 'Method Name' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'integMode', label: 'Mode', tableHidden: true },
      { key: 'recActivityName', label: 'Activity Name', tableHidden: true },
      { key: 'bankAccNumber', label: 'Bank Acc #', tableHidden: true },
    ],
  },
  'fusion-apply-receipts': {
    title: 'Fusion Apply Receipts',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'receiptNumber', label: 'Receipt #' },
      { key: 'txnNumber', label: 'Txn #' },
      { key: 'accountingDate', label: 'Accounting Date', type: 'date' },
      { key: 'applicationDate', label: 'Application Date', type: 'date' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'integMode', label: 'Mode', tableHidden: true },
      { key: 'txnSource', label: 'Txn Source', tableHidden: true },
    ],
  },
  'fusion-journal-headers': {
    title: 'Fusion Journal Headers',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'ledgerId', label: 'Ledger ID', type: 'number' },
      { key: 'batchName', label: 'Batch Name' },
      { key: 'accountingDate', label: 'Accounting Date', type: 'date' },
      { key: 'customerType', label: 'Customer Type' },
      { key: 'cashCredit', label: 'Cash/Credit' },
      { key: 'integMode', label: 'Mode', tableHidden: true },
      { key: 'batchDescription', label: 'Batch Desc', tableHidden: true },
      { key: 'txnNumber', label: 'Txn #', type: 'number', tableHidden: true },
    ],
  },
  'fusion-journal-lines': {
    title: 'Fusion Journal Lines',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'jeHeaderId', label: 'JE Header ID', type: 'number' },
      { key: 'jeLineNum', label: 'Line #', type: 'number' },
      { key: 'ledgerId', label: 'Ledger ID', type: 'number' },
      { key: 'enteredCrAmount', label: 'CR Amount', type: 'number' },
      { key: 'enteredDrAmount', label: 'DR Amount', type: 'number' },
      { key: 'currencyCode', label: 'Currency' },
      { key: 'segment1', label: 'Seg 1', tableHidden: true },
      { key: 'segment2', label: 'Seg 2', tableHidden: true },
      { key: 'segment3', label: 'Seg 3', tableHidden: true },
      { key: 'segment4', label: 'Seg 4', tableHidden: true },
      { key: 'taxCode', label: 'Tax Code', tableHidden: true },
      { key: 'salesOrder', label: 'Sales Order', tableHidden: true },
    ],
  },
  'fusion-inv-txns': {
    title: 'Fusion Inventory Transactions',
    fields: [
      ...SYS_FIELDS,
      { key: 'status', label: 'Status' },
      { key: 'region', label: 'Region', required: true },
      { key: 'itemNumber', label: 'Item #' },
      { key: 'organizationName', label: 'Organization' },
      { key: 'txnDate', label: 'Txn Date', type: 'date' },
      { key: 'txnQty', label: 'Qty', type: 'number' },
      { key: 'txnUom', label: 'UOM', tableHidden: true },
      { key: 'txnSourceName', label: 'Source', tableHidden: true },
      { key: 'subInventory', label: 'Subinventory', tableHidden: true },
      { key: 'integMode', label: 'Mode', tableHidden: true },
    ],
  },
  'backup-sales': {
    title: 'Backup VendHQ Sales',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'invoiceNumber', label: 'Invoice #' },
      { key: 'outletName', label: 'Outlet' },
      { key: 'saleDate', label: 'Sale Date', type: 'date' },
      { key: 'totalPrice', label: 'Total Price', type: 'number' },
      { key: 'totalTax', label: 'Total Tax', type: 'number' },
      { key: 'region', label: 'Region' },
      { key: 'customerType', label: 'Customer Type' },
      { key: 'version', label: 'Version', type: 'number', tableHidden: true },
    ],
  },
  'backup-line-items': {
    title: 'Backup VendHQ Line Items',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'invoiceNumber', label: 'Invoice #' },
      { key: 'lineNumber', label: 'Line #', type: 'number' },
      { key: 'itemNumber', label: 'Item #' },
      { key: 'itemName', label: 'Item Name' },
      { key: 'quantity', label: 'Qty', type: 'number' },
      { key: 'totalPrice', label: 'Price', type: 'number' },
      { key: 'region', label: 'Region' },
      { key: 'saleDate', label: 'Sale Date', type: 'date' },
    ],
  },
  'backup-payments': {
    title: 'Backup VendHQ Payments',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'invoiceNumber', label: 'Invoice #' },
      { key: 'paymentType', label: 'Payment Type' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'currency', label: 'Currency' },
      { key: 'region', label: 'Region' },
      { key: 'saleDate', label: 'Sale Date', type: 'date' },
    ],
  },
  'backup-promotions': {
    title: 'Backup VendHQ Promotions',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'invoiceNumber', label: 'Invoice #' },
      { key: 'lineNumber', label: 'Line #', type: 'number' },
      { key: 'name', label: 'Promotion Name' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'region', label: 'Region' },
      { key: 'saleDate', label: 'Sale Date', type: 'date' },
    ],
  },
  'sale-sync-status': {
    title: 'Sale Sync Status',
    readOnly: true,
    fields: [
      { key: 'saleId', label: 'Sale ID' },
      { key: 'outletId', label: 'Outlet ID' },
      { key: 'saleDate', label: 'Sale Date', type: 'date' },
      { key: 'status', label: 'Status' },
      { key: 'syncAttempts', label: 'Attempts', type: 'number' },
      { key: 'lastSyncAt', label: 'Last Sync', type: 'date' },
      { key: 'oracleInvoiceId', label: 'Oracle Invoice ID' },
      { key: 'errorMessage', label: 'Error', tableHidden: true },
      { key: 'updatedAt', label: 'Updated', type: 'date' },
    ],
  },
  'backup-odoo-orders': {
    title: 'Backup Odoo Orders',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'orderName', label: 'Order Name' },
      { key: 'branchId', label: 'Branch ID', type: 'number' },
      { key: 'branchName', label: 'Branch Name' },
      { key: 'dateOrder', label: 'Order Date', type: 'date' },
      { key: 'amountTotal', label: 'Amount Total', type: 'number' },
      { key: 'amountTax', label: 'Amount Tax', type: 'number' },
      { key: 'state', label: 'State' },
      { key: 'partnerId', label: 'Partner ID', type: 'number', tableHidden: true },
      { key: 'partnerName', label: 'Partner Name', tableHidden: true },
      { key: 'timezone', label: 'Timezone', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
      { key: 'updatedAt', label: 'Updated', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'backup-odoo-order-lines': {
    title: 'Backup Odoo Order Lines',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'lineId', label: 'Line ID', type: 'number' },
      { key: 'productId', label: 'Product ID', type: 'number', tableHidden: true },
      { key: 'productName', label: 'Product Name' },
      { key: 'qty', label: 'Qty', type: 'number' },
      { key: 'priceUnit', label: 'Unit Price', type: 'number' },
      { key: 'priceSubtotal', label: 'Subtotal', type: 'number' },
      { key: 'priceSubtotalIncl', label: 'Subtotal (incl. tax)', type: 'number', tableHidden: true },
      { key: 'discount', label: 'Discount', type: 'number', tableHidden: true },
      { key: 'parentOrderId', label: 'Parent Order ID', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'backup-odoo-order-payments': {
    title: 'Backup Odoo Order Payments',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'paymentId', label: 'Payment ID', type: 'number' },
      { key: 'paymentName', label: 'Payment Method' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'parentOrderId', label: 'Parent Order ID', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'api-endpoint-configs': {
    title: 'API Endpoint Configurations',
    fields: [
      ...SYS_FIELDS,
      { key: 'service', label: 'Service', required: true },
      { key: 'name', label: 'Name', required: true },
      { key: 'path', label: 'Path / URL', required: true },
      { key: 'method', label: 'HTTP Method' },
      { key: 'apiVersion', label: 'API Version' },
      { key: 'description', label: 'Description', type: 'textarea', tableHidden: true },
      { key: 'region', label: 'Region' },
      { key: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  'ibq-credentials': {
    title: 'IBQ Credentials',
    fields: [
      ...SYS_FIELDS,
      { key: 'baseUrl', label: 'Base URL', required: true },
      { key: 'apiKey', label: 'API Key', required: true },
      { key: 'region', label: 'Region', required: true },
      { key: 'companyId', label: 'Company ID', type: 'number' },
      { key: 'active', label: 'Active', type: 'boolean' },
      { key: 'lastSyncAt', label: 'Last Sync At', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'backup-ibq-orders': {
    title: 'Backup IBQ Orders',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'orderName', label: 'Order Name' },
      { key: 'posReference', label: 'POS Reference' },
      { key: 'region', label: 'Region' },
      { key: 'companyId', label: 'Company ID', type: 'number', tableHidden: true },
      { key: 'companyName', label: 'Company Name', tableHidden: true },
      { key: 'branchId', label: 'Branch ID', type: 'number' },
      { key: 'branchName', label: 'Branch Name' },
      { key: 'posConfigId', label: 'POS Config ID', type: 'number', tableHidden: true },
      { key: 'posConfigName', label: 'POS Config Name', tableHidden: true },
      { key: 'dateOrder', label: 'Order Date', type: 'date' },
      { key: 'amountTotal', label: 'Amount Total', type: 'number' },
      { key: 'amountTax', label: 'Amount Tax', type: 'number', tableHidden: true },
      { key: 'amountPaid', label: 'Amount Paid', type: 'number', tableHidden: true },
      { key: 'state', label: 'State' },
      { key: 'partnerId', label: 'Partner ID', type: 'number', tableHidden: true },
      { key: 'partnerName', label: 'Partner Name', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'backup-ibq-order-lines': {
    title: 'Backup IBQ Order Lines',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'lineId', label: 'Line ID', type: 'number' },
      { key: 'region', label: 'Region' },
      { key: 'productId', label: 'Product ID', type: 'number', tableHidden: true },
      { key: 'productName', label: 'Product Name' },
      { key: 'qty', label: 'Qty', type: 'number' },
      { key: 'priceUnit', label: 'Unit Price', type: 'number' },
      { key: 'priceSubtotal', label: 'Subtotal', type: 'number' },
      { key: 'priceSubtotalIncl', label: 'Subtotal (incl. tax)', type: 'number', tableHidden: true },
      { key: 'discount', label: 'Discount', type: 'number', tableHidden: true },
      { key: 'parentOrderId', label: 'Parent Order ID', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
  'backup-ibq-order-payments': {
    title: 'Backup IBQ Order Payments',
    fields: [
      { key: 'id', label: 'ID', readOnly: true, tableHidden: true },
      { key: 'orderId', label: 'Order ID', type: 'number' },
      { key: 'paymentId', label: 'Payment ID', type: 'number' },
      { key: 'region', label: 'Region' },
      { key: 'paymentName', label: 'Payment Method' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'parentOrderId', label: 'Parent Order ID', tableHidden: true },
      { key: 'createdAt', label: 'Created', type: 'date', readOnly: true, tableHidden: true },
    ],
  },
};
